name: Install and build
description: Install and build applications

runs:
  using: composite
  steps:
    - name: Use Node.js v16.14.2
      uses: actions/setup-node@v3
      with:
        node-version: '16.14.2'
        registry-url: https://npm.pkg.github.com
        cache: npm
        cache-dependency-path: '**/package-lock.json'

    - name: Get node-modules from cache
      id: node-modules-cache
      uses: actions/cache@v3
      with:
        path: |
          ./node_modules
          **/node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

    - name: Install dependencies
      if: steps.node-modules-cache.outputs.cache-hit != 'true'
      uses: bahmutov/npm-install@v1
