name: Build and Deploy

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install dependencies and build applications
        uses: ./.github/actions/prepare

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifact@${{ github.run_number }}
          path: ${{ github.workspace }}/apps/*/dist
          if-no-files-found: error
          retention-days: 14

  lint:
    name: Full project lint
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Restore from cache
        uses: ./.github/actions/prepare

      - name: Run linting
        run: npm run lint

  unit-test:
    name: Unit test
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Restore from cache
        uses: ./.github/actions/prepare

      - name: Run unit tests
        shell: bash
        run: npm run test -- -- . --coverage
        env:
          CI: true
