name: Pull Request

on: [pull_request]

jobs:
  build-and-deploy:
    name: PR
    uses: ./.github/workflows/build-and-deploy.yml
    needs: get-ticket-number
    secrets: inherit
    with:
      environment: dev
      ticketNumber: ${{ needs.get-ticket-number.outputs.ticket-number }}
